# Generated by Django 4.2.1 on 2023-05-07 14:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("app_maksim_berezovik", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.TextField(
                blank=True,
                help_text="Введите контакт в формате <Имя> <Фамиля>",
                null=True,
                unique=True,
                verbose_name="Имя контакта",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.TextField(
                blank=True,
                help_text="Вводите номер в формате <код страны>"
                "<код опреатора><номертелефона>",
                null=True,
                unique=True,
                verbose_name="Номер контакта",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="user_id",
            field=models.TextField(verbose_name="Id контакта"),
        ),
    ]
