# Generated by Django 4.2.1 on 2023-05-05 23:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Полное имя",
                    ),
                ),
                (
                    "phone",
                    models.TextField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Телефон",
                    ),
                ),
            ],
        ),
    ]
