# Generated by Django 4.2.1 on 2023-05-17 18:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("app_alexander_sidorov", "0002_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField(unique=True)),
                (
                    "contacts",
                    models.ManyToManyField(to="app_alexander_sidorov.contact"),
                ),
            ],
        ),
    ]
