# Generated by Django 4.2.1 on 2023-05-24 17:57

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("app_alexander_sidorov", "0003_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
