version: '3'

output: 'prefixed'

tasks:

  gen-cert:
    cmds:
      - >
        openssl req -x509
        -out certs/m-pt1-63-23.local.crt
        -keyout certs/m-pt1-63-23.local.key
        -newkey rsa:2048 -nodes -sha256
        -subj '/CN=m-pt1-63-23.local' -extensions EXT -config <( printf "[dn]\nCN=m-pt1-63-23.local\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:m-pt1-63-23.local\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
      - >
        openssl req -x509
        -out certs/docs.m-pt1-63-23.local.crt
        -keyout certs/docs.m-pt1-63-23.local.key
        -newkey rsa:2048 -nodes -sha256
        -subj '/CN=docs.m-pt1-63-23.local' -extensions EXT -config <( printf "[dn]\nCN=docs.m-pt1-63-23.local\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:docs.m-pt1-63-23.local\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
      - >
        openssl req -x509
        -out certs/dba.m-pt1-63-23.local.crt
        -keyout certs/dba.m-pt1-63-23.local.key
        -newkey rsa:2048 -nodes -sha256
        -subj '/CN=dba.m-pt1-63-23.local' -extensions EXT -config <( printf "[dn]\nCN=dba.m-pt1-63-23.local\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:dba.m-pt1-63-23.local\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")

    desc: generate certificates for m-pt1-63-23.local
    dir: "{{.ROOT_DIR}}"
